version: "3"
services:
  sausage_bot:
    container_name: sausage_bot
    hostname: sausage_bot
    image: geirawsm/sausage_bot:latest
    restart: unless-stopped
    volumes:
      - /path/to/your/local/data-folder:/data
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD=${DISCORD_GUILD}
      - BOT_ID=${BOT_ID}
