version: "3"
services:
  sausage_bot:
    container_name: sausage_bot
    hostname: sausage_bot
    image: geirawsm/sausage_bot:latest
    restart: unless-stopped
    volumes:
      - /path/to/your/local/data-folder:/data
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD=${DISCORD_GUILD}
      - BOT_ID=${BOT_ID}
      - BOT_CHANNEL=${BOT_CHANNEL}
      - PREFIX=${PREFIX}
      - ADMIN_GUILD_ID=${ADMIN_GUILD_ID}
      - ADMIN_CHANNEL_ID=${ADMIN_CHANNEL_ID}
      - LOG_ROTATION_DAYS=${LOG_ROTATION_DAYS}
      - SPOTIFY_ID=${SPOTIFY_ID}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
      - SCRAPEOPS_API_KEY=${SCRAPEOPS_API_KEY}
