name: Build, test and deploy bot

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  test_build_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade flake8 pipenv

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pipenv install --dev
        pipenv run python -m pytest

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{secrets.DOCKER_USER}}/sausage_bot

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        file: ./dockerfile
        tags: ${{ secrets.DOCKER_USER }}/sausage_bot:${{ github.ref_name }}
        labels: |
          Last run number=${{ github.run_number }}
          Last commit=${{ github.sha }}
          Branch=${{ github.ref_name }}
        build-args: |
          LAST_RUN_NUMBER=${{ github.run_number }}
          LAST_COMMIT=${{ github.sha }}
          BRANCH=${{ github.ref_name }}
